import React from 'react';
import Head from 'next/head';

export function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app aaaa" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hola</h1>
    </div>
  );
}
